robot_frame: "base_link"
map_frame: "map"
map_center_x: -7.5
map_center_y: -7.5
map_size_x: 15
map_size_y: 15
map_resolution: 0.1
map_publish_freq: 1.0
update_movement: 0.1
drone_col_rad: 0.3
obs_col_rad: 0.5
dir_enable: true
fake_obs: false