robot_frame: "base_link"
map_frame: "map"
map_center_x: -2.5
map_center_y: -2.5
map_size_x: 5
map_size_y: 5
map_resolution: 0.1
map_publish_freq: 1.0
update_movement: 0.1
drone_col_rad: 0.35
obs_col_rad: 0.4
dir_enable: false
fake_obs: false