node_name: "rob498_drone_07"
offset: 0.05
land_offset: -0.3
launch_height: 1.5
vicon_enabled: false
rate: 20
vis: true
error_tol: 0.13
unlimited_waypts: true
rotate_angle: 0.785398 # 0.523599 30 degree 0.785398 45 degree  1.0472 60 degree  1.5708 90 degree
length_pause: 30
test_vicon: false